version: '3.8'

services:
  app:
    container_name: react-nginx
    image: docker-react-nginx
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173